"""upload

Revision ID: 057e3f6e3b71
Revises: 
Create Date: 2025-03-22 00:56:40.537525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057e3f6e3b71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('field_name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column('field_name')
        batch_op.drop_column('step')

    # ### end Alembic commands ###
